# version: '3.9'

services:
  nginx:
    image: andriikhomik/taskify-app:nginx-latest
    restart: always
    depends_on:
      - client
      - server
    ports:
      - "80:80"
    networks:
      - node-network

  client:
    image: andriikhomik/taskify-app:client-latest
    env_file:
      - variables.env
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - node-network

  server:
    image: andriikhomik/taskify-app:server-latest
    env_file:
      - variables.env
    ports:
      - "8000:8000"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
  # Grafana image
  # version: "3.8"
  # services:
  #   grafana:
  #     image: grafana/grafana:latest
  #     container_name: grafana
  #     restart: unless-stopped
  #     environment:
  #       - TERM=linux
  #       - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-polystat-panel
  #     ports:
  #       - '3000:3000'
  #     volumes:
  #       - 'grafana_storage:/var/lib/grafana'
  # volumes:
  #   grafana_storage: {}
