# version: '3.9'

services:
  nginx:
    depends_on:
      - client
      - server
    image: andriikhomik/taskify-app:nginx-latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - node-network

  client:
    depends_on:
      - server
    image: andriikhomik/taskify-app:client-latest
    build: 
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    env_file: ./.env
    container_name: client
    environment:
      - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    stdin_open: true
    tty: true
    networks:
      - node-network

  server:
    image: andriikhomik/taskify-app:server-latest
    container_name: server
    restart: always
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
    networks:
      - node-network

networks:
  node-network:
  # Grafana image
  # version: "3.8"
  # services:
  #   grafana:
  #     image: grafana/grafana:latest
  #     container_name: grafana
  #     restart: unless-stopped
  #     environment:
  #       - TERM=linux
  #       - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-polystat-panel
  #     ports:
  #       - '3000:3000'
  #     volumes:
  #       - 'grafana_storage:/var/lib/grafana'
  # volumes:
  #   grafana_storage: {}
