name: Build React app
run-name: ${{github.actor}} has triggered the pipeline

on: 
  push:
      branches: [master]

jobs:
  react-app:
    runs-on: ubuntu-20.04
    strategy:
      matrix: 
        node: [16]
    name: Node ${{matrix.node}} sample
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with: 
          node-version: ${{matrix.node}}
      - run: npm ci