name: Build React app
run-name: ${{ github.actor }} has triggered the pipeline

on:
  push:
    branches: [master, main, dev]
  pull_request:
    branches: [master, main, dev]

jobs:
  lint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [16]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

  build-and-deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [16]
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Build Docker image
        run: |
          docker build -t andriikhomik/taskify-app:client-${{ github.run_number }} -t andriikhomik/taskify-app:client-latest .

      - name: Log in do Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images to Docker Hub
        run: |
          docker push andriikhomik/taskify-app:client-${{ github.run_number }}
          docker push andriikhomik/taskify-app:client-latest

  deploy-nginx:
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build NGINX Docker Image
        working-directory: ./nginx
        run: |
          docker build -t andriikhomik/taskify-app:nginx-${{ github.run_number }} -t andriikhomik/taskify-app:nginx-latest .

      - name: Log in do Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images to Docker Hub
        run: |
          docker push andriikhomik/taskify-app:nginx-${{ github.run_number }}
          docker push andriikhomik/taskify-app:nginx-latest

  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          driver-opts: |
            image=moby/buildkit:v0.10.6

      - name: Log into registry
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: quickview,cves
          only-severities: critical,high
          sarif-file: scout-report.sarif

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: docker-scout-findings
          path: scout-report.sarif

  security:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: snyk-findings
          path: snyk.sarif
